### PR TITLE
The React Native Community guidelines

### PR DESCRIPTION
**Pull request by kelset**
I'll be honest - creating this document was always in my mind since the start of this repository.

We are at a phase where we need to reinforce the foundation of what we do and how we do it, following all the new code influx from the Lean Core effort.

Once this PR is approved, here's a rough plan I was thinking about:
- renaming this repo to `meta` and doing some house chores to reflect it (etc, rewording the READMEs, etc)
- created a gSheet file with all the maintainers, which repo they are working on and how to reach out to them in order to keep an eye on how things are moving
- adding a `guidelines` folder with all the different guidelines for the community (there are currently 3 being drafted: Repository Maintenance, Project Setup, Community Management)
- enforce the new guidelines; this should be mostly easy thanks to direct communication and the fact that GitHub allows for [organization-wide community health files](https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/)

If you have any feedback, anything that you feel it's missing, please write a comment here so that the conversation can continue.

---

### Acknowledgements
Thanks to @grabbou @salakar and @Titozzz for early feedback.

This document is inspired by, among other files, the [ocaml community manifesto](https://github.com/ocaml-community/meta).

### CODE REVIEW

**Comment by pvinis** [comment]
I like the text and the ideas for next steps. My main concern would be to make sure we have this gsheet and ways to contact people that maintain and develop the repos of this org, but moreover I think it would be very cool if more than just one person is able and enabled to help in case the current maintainer is unable to continue for example. I would be very sad if say in a year, some library here is stale and outdated. Maybe part of the guidelines should be to have "regular" checks of the live-ness of the repos here, and prevent any problems with that by having the rest of the community help with that.  Does that make sense?

**Comment by IljaDaderko** [comment]
Definitely a good idea, it would be good to have consistent project structures / readmes across the packages and additional things like podspec files for ios installations.

**Comment by Eyesonly88** [comment]
Thanks for starting this discussion.
Another idea is to have a way to elect primary and secondary maintainers (or more). So we can share the load and participate as necessary. For example, someone could be available to help with docs/reviews in November / December etc...

**Comment by cpojer** [comment]
Thanks for kicking this off! @hramos and I have also started a similar write up from within FB but it's still in the draft stage. I'll be off for a week but will work on putting it together and sharing it more widely soon.

**Comment by kelset** [comment]
@cpojer I was aware of FB doing some work around the contribution guidelines, but nothing strictly connected to this. If it's more connected it may be worth a catchup privately.

re: maintainers (cc @pvinis @Eyesonly88)
I absolutely share your concerns, in my current guideline draft (I've added the titles in the first post) for maintainers, ideally there would always be at least 2, best 3 per each. We can discuss the details once there is a PR for the guidelines for that 🤗

**Comment by grabbou** [comment]
@cpojer we also started working with @kelset on guidelines for maintainers (which is something I believe we have talked about) and it might be wroth to catch up on that when we are all in London in 2 weeks.

Looking forward to seeing the results of your work soon!

**Comment by ashfurrow** [comment]
This is great! I like the changes and the next steps.

Not to throw a wrench in things, but I would like to mention the [Moya contributor guidelines](https://github.com/Moya/contributors) that @orta and I helped develop. I have rolled out those guidelines successfully in [RxSwiftCommunity](https://github.com/RxSwiftCommunity/), a very similar GitHub organization to react-native-community.

The tl;dr of the Moya guidelines are: when someone gets their first pull request merged, they get invited to the org. We totally [automate this invitation process with Peril](https://github.com/RxSwiftCommunity/peril/blob/master/org/aeryn.ts). This gives them a sense of ownership and motivates them to continue contributing (and to help review issues and pull requests, the less glamorous parts of OSS). I know react-native-community is operating a larger scale than Moya or the RxSwiftCommunity, but I'm _very_ excited at the prospect of seeing these guidelines rolled out in RN.

**Comment by kelset** [comment]
hey everyone, thanks for all the feedback - after IRL conversations among FB members and the other members of the RNComm, we agreed that it's actually best to have this as its own separate repo, which has been already created:

https://github.com/react-native-community/meta

Also, we have removed the "manifesto" wording because it has some negative connotation is some cultures and we want to avoid issues because of that.

You'll also be able to find "stubs" for the guidelines we were already considering, so that you can check what each .md will be about - the details will be filled & discussed through PRs.

See you over there 👋

**Pull request closed without merging**
