### PR TITLE
Persistent Scrollbars (Android only)

### PR DESCRIPTION
**Pull request by kpsroka**
Expose Android's `setScrollbarFadingEnabled` via a ScrollView prop.

### CODE REVIEW

**Comment by axe-fb** [comment]
cc @mdvacca, @ayc1

**Comment by axe-fb** [comment]
@ayc1 said it looks good. Should we get a PR and get this done ?

**Comment by jamonholmgren** [comment]
@kpsroka This looks good to me! IMO, this is a small and non-breaking change, so it probably can just be a pull request on the main repo rather than an RFC. If there's sufficient push-back about it there then we can turn it into an RFC.

**Comment by axe-fb** [comment]
closing this issue - will wait for the PR on the main repo. If the PR takes time, ping me, and i can fast track the process

**Comment by grabbou** [comment]
FYI @axe-fb, a PR has been submitted: https://github.com/facebook/react-native/pull/22300

**Pull request closed without merging**
