### PR TITLE
Official Android Docker for react native

### PR DESCRIPTION
**Pull request by gengjiawen**
Provide an official docker to the community and make the ci easier.

### CODE REVIEW

**Comment by kelset** [comment]
👋 @gengjiawen!

If I understand correctly, this would mean maintain like a docker image in the registry/marketplace so that people can just write something like `FROM react_native_android:latest` in their Dockerfile, right?

Does it mean that we should have a version of the image per each RN release?

**Comment by gengjiawen** [comment]
Yes, you are right, just import the image and add the build script is enough.

Actually if we have not touch the `Dockerfile`, there is no need to publish a new one.

But if we hook the publish docker script when we draft a new release, it maybe easier this way by not publishing the docker manually.

**Comment by axe-fb** [comment]
Does this have to be a part of core react native ? Can it not live separately in react-native-community ?

**Comment by gengjiawen** [comment]
yes, I think it can move out.

**Comment by satya164** [comment]
@gengjiawen lemme know if you want to create a repo in react-native-community. I can help with that.

**Comment by axe-fb** [comment]
@gengjiawen  - Once we have moved it out, can we also delete the images from the core repo ?

**Comment by axe-fb** [comment]
Should we close this issue since we have a resolution for it ?

**Comment by gengjiawen** [comment]
> Once we have moved it out, can we also delete the images from the core repo ?

Yes, maybe remove some script in `package.json`, but I need @hramos opinion on this.

> Should we close this issue since we have a resolution for it ?

Maybe not for now, I want this to get community know this more and discuss how this pr will go.


> @gengjiawen lemme know if you want to create a repo in react-native-community. I can help with that.

Not for now, but maybe later, I will let you know if it needs, thanks.

**Comment by gengjiawen** [comment]
I don't want to maintain two same file in two repo, is the dockerfile used internally at facebook @axe-fb ?

**Comment by gengjiawen** [comment]
@satya164 Can you create a repo for me, I think I want to try it in community due to https://github.com/facebook/react-native-website/issues/653.

**Comment by sibelius** [comment]
https://twitter.com/sseraphini/status/1061919273113829376

We have this docker image https://github.com/entria/docker-react-native-android

we've been using it on some open source projects like react-native-camera and react-native-share

**Comment by gengjiawen** [comment]
@sibelius The docker is intended to do more then build an react native android app, it also has the ability to build and test react native source code.

**Comment by axe-fb** [comment]
@gengjiawen  - what are the next steps on this proposal ?

**Comment by gengjiawen** [comment]
@axe-fb I need @hramos opinion on this, to see whether or not move the Dockerfile out of the main repo.

**Comment by axe-fb** [comment]
@gengjiawen  - should we merge this PR, since we will now be acting upon the proposal ?

**Comment by gengjiawen** [comment]
I think it can merge.

**Pull request merged**
