### PR TITLE
Add possibility to trigger animation on touchable events bypassing js thread.

### PR DESCRIPTION
**Pull request by vaukalak**
Unfortunately js thread and the bridge are still bottleneck for some of animations, this proposal attempts to fix that for touchable-driven animations.

### CODE REVIEW

**Comment by patrickkempff** [comment]
I like this approach! 

I am wondering how the duration of the pressIn animation should be determined? Is it by using the `duration` param of the animation? or as long as the user holds the touchable? 

Let's say we use duration param of the animation itself, what happens to the animation when use user releases the touchable? does it cancel the  animation and starts the pressOut animation? How to make those seamless?

Also does passing animations to pressIn/pressOut only work with TouchableWithoutFeedback? Or also with the others like TouchableOpacity and TouchableNativeFeedback? What happens to the existing animations of those components?

**Comment by vaukalak** [comment]
@patrickkempff so as we pass `AnimationConfig`, the duration is already there. And yes, animation will be stopped, when button has been released. I think `TouchableOpacity` and `TouchableNativeFeedback` will benefit of this api, cause their animations will be also more performant when using this approach. Anyway this brings me to think that maybe `pressIn` and `pressInAnimation` should be probably different properties, otherwise it will be impossibe to subscribe to touchable opacity `pressIn`.

**Comment by brentvatne** [comment]
i don't believe that this is possible with the existing gesture system because almost all of the logic is performed in js. you can build this already today by using react-native-gesture-handler and react-native-reanimated though, and then build the same api you're proposing on top of that.

**Comment by vaukalak** [comment]
@brentvatne so you mean, that, when I have code like
```
const scrollY = new Animated.Value(0);
...
<ScrollView
    style={styles.fill}
    scrollEventThrottle={16}
    onScroll={Animated.event(
      [{nativeEvent: {contentOffset: {y: scrollY}}}]
    )}
  >
```
All updates of scrollY internal value will still happen on js?

**Comment by brentvatne** [comment]
well yes in this case it will because you didn't add `useNativeDriver` to the `Animated.event` - but also `ScrollView` is different from `Touchable*` because its gestures are managed by native, which makes this possible. `onPress` on `Touchable*` originates from JS code that processes touch events, whereas `onScroll` originates from native and is later dispatched as an event to JS.

**Comment by brentvatne** [comment]
i'd direct efforts towards this issue instead: https://github.com/kmagiera/react-native-gesture-handler/issues/358

it's possible to implement this type of behavior right now using other gesture-handlers made available through this pkg, and will be quite easy to build something like the touchable api you mentioned above once the issue is resolved.

**Comment by vaukalak** [comment]
@brentvatne thanks for the feedback.

**Pull request closed without merging**
